### ISSUE TITLE
Question: So how to use the docker images?

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-docker#5]
On docker I see multiple docker images like apicurio-studio-ws -api -ui -auth. They all have no readme at all but they have 10M+ pulls. Feeling like an idiot now, but unlike the other 10M people I just do not find the documentation for those images. It's even not clear to me, what the difference between those 4 is. Which ones do I need and do I have to link them somehow?
As little as 5 lines of documentation would help a lot!

**Comment by EricWittmann** [comment]
Apicurio is the most successful project in history!  10M pulls on docker hub.  :) :)

These docker images are a little bit internal at the moment, but the only reason for that is the lack of documentation.  I'll try to put together an article about the docker images and also add some appropriate README files for them.

**Comment by EricWittmann** [comment]
Oh, and while you wait, the source for the various Apicurio docker images can be found here:

(the three primary images)
https://github.com/Apicurio/apicurio-studio/tree/master/platforms/swarm

(the auth image and an OpenShift template)
https://github.com/Apicurio/apicurio-studio/tree/master/distro/openshift

That may help a bit if you're in a rush.

**Comment by EricWittmann** [comment]
OK I've updated the documentation on docker hub.  @0815fox can you check to see if it makes sense and is useful? 

I'm also working on an article for the Apicurio documentation that will be a higher level explanation of e.g. how to run Apicurio on OpenShift (which would include docker info).  Don't have an ETA on that yet, will be writing it a bit here and there as I have time.

**Comment by 0815fox** [comment]
Wow, you are so fast with that. I scheduled a time slot to check this out this afternoon.

**Comment by EricWittmann** [comment]
I should have an architectural diagram as part of the documentation article...

**Comment by 0815fox** [comment]
I started to write a docker-compose script for that, however, it will take me some more time. As of now I also tried apicurio/apicurio-studio to avoid the complex setup.

However, that image still suffers from https://github.com/Apicurio/apicurio-docker/issues/3.

For the moment I will continue to use the local installation.

**Comment by 0815fox** [comment]
In docker containers can also be linked into a network, in simple cases using the link command line option. Anyway, for the moment I will continue with the local installation and as soon as I get a virtual machine for that (actually they scheduled that task for november), I will probably set this up using docker. It will work, I am sure. Thank you a lot for that input.

**Comment by EricWittmann** [comment]
Well that'd be great.  If you are allowed to contribute the docker-compose script back to this project I'd really appreciate it.

**Comment by EricWittmann** [comment]
Some additional documentation is ready for you to have a look at.  You can find it here:

https://apicurio-studio.readme.io/v0.2.15/docs/running-apicurio-on-openshift-or-docker#section-installing-in-openshift

Please let me know if it's helpful or not.  Any additional information you might need can be added - just tell me what's missing. :)

**Comment by 0815fox** [comment]
The component diagram is really helpful, thank you. We are still in the phase of evaluating tools though.
